### PR TITLE
Update some game.xml-files to implement correct unit repair

### PR DESCRIPTION
**Pull request by panther2**
This PR is based on https://github.com/triplea-game/triplea/issues/2256
and addresses #24 .

While there I took care of #23 too .

### CODE REVIEW

**Comment by panther2** [comment]
@ron-murhammer Please take a look, Thank you.

**Comment by ron-murhammer** [comment]
@panther2 Looks good. Merging.

**Comment by panther2** [comment]
@ron-murhammer 
Can we already update this map in the `triplea_maps.yaml` ?
Just wondering, because people on the latest "stable" (3635) don't have the necessary engine code changes (https://github.com/triplea-game/triplea/pull/2370 and https://github.com/triplea-game/triplea/pull/2373 ) ...

**Comment by ron-murhammer** [comment]
@panther2 So the engine should be able to handle the map changes (will mostly just ignore them til the engine changes are released). 

That being said the one thing I'm not sure on is whether the map changes will cause games to not be compatible (game started before the game.xml changes may not work after folks update). You may want to test that out and if it isn't compatible then probably definitely want to increment the version of the maps in the game.xml.

**Comment by panther2** [comment]
@ron-murhammer 

IMHO existing savegames always include the logic of the "initial" xml the games have been started with, so just an update of the map.xml should not break savegames. My understanding is that savegames can only be broken in case of engine updates. Is that correct?

Anyway, I did a brief testing of the following circumstances:

1.
People downloading "stable" 3635 today and the map for the first time will get the updated (latest) map version anyway, regardless of the versioning in the yaml. So I simply tested this scenario, did some turns and found out that there are no problems except some repair issues not being resolved correctly - but that has been the status quo anyway (and will be resolved only by the engine update).

2. 
I downloaded arbitrary savegames from the "Play Boardgames" section of axisandallies.org and opened them 
a) in 3635 (with the latest map versions) - I experienced no further problems (apart from repair issues)
b) in 6693 (with the latest map versions) - I experienced no further problems (apart from repair issues)

There were no crashes and no console errors in any scenario.

So it looks like having the new map files "productive" does not remarkably downgrade the situation until the engine will get its next stable status.

I am not sure, if my testing covered every scenario possibly problematic, though.

Please indicate if you want me to test anything else/special.

**Comment by ron-murhammer** [comment]
@panther2 I believe you are correct. Please go ahead and submit a PR to increment the version in triplea_maps.yaml.

**Comment by simon33-2** [comment]
There can be problems if things are removed from the other parts of the map package though. e.g. if images are renamed or removed. Or with objectives.

**Pull request merged**
