### PR TITLE
ww2global40_balanced2_0 - bomber cost revision

### PR DESCRIPTION
**Pull request by regularkyd**
Hi there! this is Regularkid from the AxisandAllies.org forum and co-creator of Balanced Mod. The mod's creators, Adam514 and I, after extensive consultation with the broader Balanced Mod community, have agreed that a revision to bomber costs is necessary to achieve the namesake of the mod--balance.  This change is coded above. Kindly substitute this xml for the existing ww2global40_balanced2_0.xml file. Because github would not allow me to submit a file with a name already in use, I added an "X" to it. Please remove this. If I need to do anything else, please let me know. Thank you!

### CODE REVIEW

**Comment by panther2** [comment]
@regularkyd If things on Github have not changed recently, you need to fork this repository, apply the change to your fork and then create a pull request to merge from your fork into this repository. Or maybe ask @simon33-2 to directly apply the change here.

IMHO the ww2global40_balanced_move1st.xml needs that change, too, doesn't it?

**Comment by regularkyd** [comment]
Thanks bruv

**Comment by regularkyd** [comment]
Hey panther. I'm still having some difficulty submitting this request, it seems. I forked the repository, I applied the change to my fork (i.e., updated the ww2global_balanced_2_0.xml file). But can't seem to convert that into a pull request to be merged into this repository. Frankly, I'm not sure where to go from here. Any help you could provide would be greatly appreciated. Here is a link to the updated file on my forked repository. Thanks! https://github.com/regularkyd/world_war_ii_global/commit/6d37963e830325a359de171c878b4f78a9e32c2a

**Comment by panther2** [comment]
@regularkyd In your fork you have succesfully applied the change. Now go to your fork and you see this:
pr
Please note the red circle that I included. Create the pull request by hitting "Pull Request". Now you should see your request to merge your change from your fork into the master branch. you can also hit "view difference" to start from there. 

I recommend to close this PR before, just to avoid confusion.
Also please apply the change to the "BM-combat move first"-XML, too. Thank you.

Good luck, it's been a while that I did that procedure, so fingers crossed ;-)

**Comment by regularkyd** [comment]
alright, thanks. I tried it again. Are you seeing the pull request? Thanks for all your help.

**Comment by panther2** [comment]
@regularkyd I can see that you created a pull request, But unfortunately you targeted your own fork instead of this original repository (master). 
What needs to be requested is to pull the change from your fork
`regularkyd/world_war_ii_global - master `
into
`triplea-maps/world_war_ii_global -master`

I hope that helps.

**Comment by regularkyd** [comment]
thanks man. is it better now?

**Comment by panther2** [comment]
While the procedure looks good now and now the new pull request is visible here, I wonder about the content of the 4 commits included there... it looks somehow redundant. But that is too much for my Github-knowledge. Maybe @ron-murhammer or @simon33-2 can take a look please...

**Comment by ron-murhammer** [comment]
@regularkyd @panther2 Are you trying to create a new version of balance mod or update the existing balance mod?

**Comment by panther2** [comment]
@ron-murhammer 
@regularkyd wanted to update some details of the existing balance mod.

**Comment by regularkyd** [comment]
Correct. We're updating the main version of Balance Mod, contained in
ww2global_balanced2_0.xml, while leaving the other variants unchanged so
players can continue to play with bombers at 12 if they choose to do so.

**Pull request merged**
