### PR TITLE
Trying to upate oztea again

### PR DESCRIPTION
**Pull request by beelee1**
confidence isn't high but here we go.

If this works do I have to update the version number on maps yaml with a description of the change ? I'll need to relearn that as well

hmm... see some other changes that i didn't do. I guess that's a history of previous ? My changes are lines:
2840
2846
2853
2859

as well as changing the version number to 3.9.1 which was for my own clarification. Should that stay 3.9 ?

Thanks

### CODE REVIEW

**Comment by ssoloff** [comment]
@beelee1 Looks much better.  It appears to be a well-formed PR. :+1:

> see some other changes that i didn't do. I guess that's a history of previous ?

My guess is you edited an older version of _Ozteas_1941_Global_Setup.xml_.  You are effectively reverting changes submitted by @simon33-2 and @panther2 since you originally added _Ozteas_1941_Global_Setup.xml_ back in February.  I would pull down the [latest version](https://raw.githubusercontent.com/triplea-maps/world_war_ii_global/master/map/games/Ozteas_1941_Global_Setup.xml) and re-apply your changes to ensure you are not changing anything unexpectedly.

> as well as changing the version number to 3.9.1 which was for my own clarification. Should that stay 3.9 ?

I don't really know what the rules are for bumping the map version in the XML.  One of the other map makers may be able to provide more details on that.  What will be important is to bump the version in the _triplea_maps.yaml_ file after your PR is merged so that users will be notified that an updated map is available.

**Comment by beelee1** [comment]
Thanks for the reply ssoloff. I started a new repo and forked off of the existing global so I think I should be up to date. I'll go over everything again

**Comment by beelee1** [comment]
I pulled the xml out of the downloaded maps folder and changed it. Made 3.9.2 for clarity. Compared it to the one in the PR and 3.9.2 shows as a change. The actual fix changes didn't show up but they are the same as the ones in the PR so I wouldn't think they would.

However the other changes I didn't make still show up. I don't really understand it but don't no how to get anything newer than the one out of the downloaded maps folder, which was downloaded in the last couple of weeks

**Comment by ssoloff** [comment]
> I pulled the xml out of the downloaded maps folder and changed it ... I don't really understand it but don't no how to get anything newer than the one out of the downloaded maps folder

Not sure why what's in your _downloadedMaps_ folder is behind, but you can use the following link to get the latest version:

https://github.com/triplea-maps/world_war_ii_global/raw/master/map/games/Ozteas_1941_Global_Setup.xml

Right click it and choose "Save Link As..." (or something like that).

**Comment by beelee1** [comment]
hmm...maybe i'm just high or something and am missing the obvious. I used your link and redid it again and the same thing happened. I changed to 3.9.3 this time. here's a screenshot.

screenshot from 2017-12-23 17-41-05

There's some other lines in red/pink as well that aren't shown.
I'm thinking that's just the way it is and my PR should be ok. Maybe ? : )

**Comment by ssoloff** [comment]
It looks like you're comparing to what's in your `oztea-yet-another-try` branch, not what's in the `master` branch.  That is, as if you were submitting another commit to that branch.  Otherwise, the old version would be "3.9", not "3.9.1".

Try this in your fork:

1. Make sure the `master` branch is selected in the branch dropdown.
1. Open the branch dropdown and type a new branch name (I'm using `ssoloff-patch-1`).  Make sure the **Create branch** button that appears says "from 'master'".  Click the **Create branch** button.
1. Navigate to the _map/games/Ozteas_1941_Global_Setup.xml_ file.
1. Click the **Edit this file** button.
1. Change the map version on line 4 from "3.9" to "3.9.1".
1. Add the four new `<option name="originalOwner" value="Dutch"/>` lines where appropriate.
1. At the bottom of the page, make sure the **Commit directly to the \<_whatever_\> branch** radio button is selected.
1. Click **Commit changes**.
1. Go back to the home page of your fork.  Make sure the branch dropdown still has your new branch selected.
1. Click the **New pull request** button.

I went through those steps and created #30.  Do those changes look correct?  If so, you should be able to follow the same steps to produce the same thing.

**Comment by beelee1** [comment]
Thank you ssoloff. That worked. At least I think it did, the pink things didn't show up.

Sorry for my incompetence. As you can tell I'm intellectually challenged here : )

**Comment by ssoloff** [comment]
@beelee1 :+1: No problem.

**Pull request closed without merging**
