### PR TITLE
Merge balanced mod into this map, create new xmls to utilise ordered …

### PR DESCRIPTION
**Pull request by simon33-2**
…combats

Incorporates: https://github.com/triplea-maps/world_war_ii_g40_balanced
So that map is no longer needed.

Also adds two new maps which utilise the combat ordering function from PR #1140

### CODE REVIEW

**Comment by panther2** [comment]
Great!

While there, what do you think about #9

**Comment by DanVanAtta** [comment]
@simon33-2  , please confirm: https://github.com/triplea-maps/world_war_ii_g40_balanced/issues/11

**Comment by DanVanAtta** [comment]
@simon33-2 , I think it was actually a mistake to merge this since the map cannot be released without an updated game engine version. There were also 3 different changes in here just about, it's better for those to be split up separately. Could you do a partial revert of the BattleDelegate change so that we can release this map with the other updates?

**Comment by simon33-2** [comment]
It doesn't take effect until we update the Project .yaml file and the maps which use the old logic are still present and unchanged. I don't see the harm done?

**Comment by DanVanAtta** [comment]
This does not use the new battle delegate? My impression was it did, in which case it would require a future version of the game engine

**Comment by simon33-2** [comment]
Yes it does but until something actually references this update it won't matter. The current .yaml file refers to the old version.

Or am I missing something?

**Comment by DanVanAtta** [comment]
The .yaml is what live game engines will pick up. None except one built with a special branch can play v21. Which means update unit images, the merge of the two maps, is being blocked by needing a new game engine version. Any further updates to this map cannot be released either, because nobody will have a compatible game engine.

**Comment by simon33-2** [comment]
Oh and since that is not in 1.9, the maps can't be updated until a new version of the engine is released. I see the problem.

**Comment by DanVanAtta** [comment]
Yeah, the compatibility system of maps, game engine, lobby needs some rethinking and a lot of work. We for some time have wanted to avoid the reflection that maps XML tags to java classes. Instead use lookup strings so that the classes are created explicitly on the java side and not via reflection.

If we could add an option flag to that is ignored by old game engines, but picked up by new ones, we would avoid this problem.

IMO now that we can easily update maps, and the game engine, we're going to see a lot more strain in places where versions all need to be kept in sync.

**Pull request merged**
