### PR TITLE
Update Ozteas_1941_Global_Setup.xml

### PR DESCRIPTION
**Pull request by beelee1**
think it worked this time

### CODE REVIEW

**Comment by ssoloff** [comment]
@beelee1 Looks good.  I converted some tabs to spaces to ensure consistency with the rest of the file (but mostly to keep my OCD at bay :smile:).

I'm not really an expert on this map, so I'm going to leave the PR open for another 24 hours to see if @simon33-2 or @panther2 have any comments.  Otherwise, I'll merge it tomorrow.

**Comment by beelee1** [comment]
> Looks good. I converted some tabs to spaces to ensure consistency with the rest of the file (but mostly to keep my OCD at bay :smile:).

heh heh Thanks for that. A tidy place is a happy space : )

**Comment by panther2** [comment]
@beelee1 @ssoloff 

The game related changes look good.

The only remark I have is that I would not touch the game version (so leave it at 3.9).
The reason is as follows:

The game version has its origin back in those days when the Global1940 (OOB) map reflected the so-called Alpha3.9-status. That was a predecessor of the final Global 2nd edition ruleset.

Until today there have been continuous changes to the this map repositories that never influenced the map version inside the xml. Actually no one (including me) ever touched the xml-game-version (3.9) for years.

So I would recommend (to all of us) to leave it untouched for now and better think of a map-versioning system that makes some sense.

**Comment by beelee1** [comment]
@panther2 
right on I'll redo it leaving at 3.9
I'll need to do the yaml thing again also. Have to relearn that too : )

**Comment by ssoloff** [comment]
> I'll redo it leaving at 3.9

@beelee1 Note that you can just edit the file in this PR--no need to redo all the changes in a new PR.

Just click the **Files changed** tab at the top of the page, then click the **Change this file using the online editor** button (pencil) like you did when you originally made the changes.  At the bottom of that page, make sure **Commit directly to the `oztea-continue-trying` branch** is selected before clicking the **Commit changes** button.

**Comment by beelee1** [comment]
Cool thanks ssoloff

**Comment by simon33-2** [comment]
I would disagree about leaving it at 3.9. That's been a bit of stupidity for a long time. You can't easily tell if you have an upgrade.

**Comment by beelee1** [comment]
@simon33-2 
that's why I changed it in the first place. So I could tell the difference. 
Anyway w/e you guys think best. Saw some people playing it on the lobby a couple weeks ago and the island issue came up. Just trying to fix it

**Comment by beelee1** [comment]
hmm...well didn't think changing 4 lines on the xml was going to be this difficult. Guess i'm just a stupid fucker.

Not a popular map but when someone gets burned after 4-6 hours of play because Java doesn't turn into US controlled and people start arguing about it ...

Sorry. I'll walk away and try again later.

**Comment by ssoloff** [comment]
@beelee1 @simon33-2 I agree with you both that updating the version seems natural and would be helpful for "bookkeeping" purposes.  However, @panther2 provides a compelling argument for why this hasn't been done in the past.  I would suggest a new issue be opened in the triplea-maps/Project repo so we can get a clear direction going forward on how the map version in the XML file should be managed.  I know @RoiExLab and @DanVanAtta have discussed this recently (albeit peripherally) in triplea-game/triplea#2637.

Since the game-related changes in this PR have received tacit approval, I'm going to go ahead and merge it.

Thanks for the fix, @beelee1!  Please follow-up with an update to the _triplea_maps.yaml_ file in the triple-game/triplea repo.

**Comment by beelee1** [comment]
Apologies again 

Thanks for merging. reading up on the yaml thing now

**Comment by beelee1** [comment]
wow. i must be a complete idiot. triplea_maps.yaml comes up as a no go. Not sure how to proceed

**Comment by ssoloff** [comment]
@beelee1 What's the no-go condition exactly?  Is it because your fork is so far behind the upstream repo?  Take a look at this [SO question](https://webapps.stackexchange.com/questions/28998/how-do-you-update-a-github-repo-fork-in-the-web-interface) which describes how you can issue a PR to your own fork to get the `master` branches in sync.  From that point, it should be identical to how you submitted this PR (obviously minus the actual changes).

Alternatively, you could delete and re-create your fork if you don't have any dangling branches in there you want to keep around.

**Comment by beelee1** [comment]
Thank you ssoloff
nothing came up when I searched it on git = the no go.
I'll try your stuff.

Thanks for your time. I know you have other things you'd prefer to do : )

**Comment by ssoloff** [comment]
No problem, @beelee1.  Teach a man to fish and all that. :smile:

> nothing came up when I searched it on git

The file you're looking for in your repo is https://github.com/beelee1/triplea/blob/master/triplea_maps.yaml (the same file in the upstream repo is https://github.com/triplea-game/triplea/blob/master/triplea_maps.yaml).

**Pull request merged**
