### PR TITLE
Adding Ozteas 1941 xml

### PR DESCRIPTION
**Pull request by beelee1**
Adding Ozteas 1941 setup for the global40 game. The game plays fine. Idk if I got all this pull request stuff right

### CODE REVIEW

**Comment by simon33-2** [comment]
Objectives don't work. Can you add the relevant lines to objectives.properties? Look at some of the existing ones to figure it out. Should be reasonably obvious.

**Comment by beelee1** [comment]
forgot to add the new one. Traveling.Will do in a couple days

**Comment by simon33-2** [comment]
Was some problem merging README.md. Have fixed that.

I'll merge it.

**Comment by simon33-2** [comment]
BTW, you also need to move on the triplea_maps.yaml in the triplea-game repo. Are you aware of this? Otherwise users won't be notified of a change when they go into Download Maps.

**Comment by beelee1** [comment]
Right on simon. Don't know why the readme gave you trouble. I just added the one sentence, but it's all new to me.

Yea not familiar with the yaml program. I think I saw something about it in one of the mapmaking links.
Ok think I found it. I'll give it a shot

**Comment by beelee1** [comment]
@simon33-2 
I forked a copy of the maps yaml. Do I just need a description and then do a pull request ? Don't mess with version or anything else ?

**Pull request merged**
