### PR TITLE
added Dutch is original owner to Dutch islands

### PR DESCRIPTION
**Pull request by beelee1**
after Japan conquers any of the islands when US reconquered it would turn back to ANZAC instead of US. I changed it to 3.9.1 but left it at xml version 1.0

### CODE REVIEW

**Comment by beelee1** [comment]
hmm..well hope I'm doing right : )

**Comment by ssoloff** [comment]
@beelee1 You committed the entire zip file instead of the individual file(s) that you modified (e.g. _*.xml_, _*.properties_, etc.).  The zip file is not actually stored in Git--it is dynamically generated only when someone downloads the map.

Feel free to ask if you need additional clarification for submitting a map change to GitHub.

**Comment by beelee1** [comment]
trying again. zip has only xml in it
[world_war_ii_global-oztea-fix.zip](https://github.com/triplea-maps/world_war_ii_global/files/1584045/world_war_ii_global-oztea-fix.zip)

**Comment by ssoloff** [comment]
@beelee1 Sorry if I wasn't clear before, but the problem is not that you are submitting a zip with the wrong content, it's that you're submitting a zip at all. :smile:

I looked at your fork and noticed a few problems.

First, you added the _Ozteas_1941_Global_Setup.xml_ file to the wrong folder.  You added it as a new file in the repo root, whereas you should just modify the existing XML file in the _map/games_ folder.

Second, your `master` branch is 31 commits behind this repo.  That means the XML file you modified may be missing several changes which have been made in the past 11 months.  In which case, merging your PR could result in a broken map.  It looks like the _map/games/Ozteas_1941_Global_Setup.xml_ hasn't been modified during that time, so you should be ok.  But, in general, you should try to keep your fork in sync with its parent repo before making any changes to avoid any merge conflicts.

My suggestion would be to do the following on your `master` branch:

1. Copy the content of the _/Ozteas_1941_Global_Setup.xml_ file to the _/map/games/Ozteas_1941_Global_Setup.xml_ file,
2. Delete the _/Ozteas_1941_Global_Setup.xml_ file.
3. Create a new PR from the `master` branch.

**Comment by beelee1** [comment]
@ssoloff 
Right on I'll give it another go. It's all pretty new to me. Did it once a year ago : )
Thanks

**Pull request closed without merging**
