### PR TITLE
ww2global_balanced2_0.xml

### PR DESCRIPTION
**Pull request by regularkyd**
Balance Mod's co-creators, after playtesting and consultation with the broader Balanced Mod community, are revising bomber costs to achieve the namesake of the mod--balance.  This change is coded in the revised xml herewith. Changes are as follows:

-Bomber cost increased to 14
-Corresponding amendment to Game Notes
-Change of version number
-Addition of Cyanight as a topper goodwill ambassador in mod credits
-Addition of a/k/a in mod credits

Thanks!

### CODE REVIEW

**Comment by panther2** [comment]
@regularkyd Would you please close this PR? 
The changes have already been merged. See https://github.com/triplea-maps/world_war_ii_global/pull/39

**Comment by simon33-2** [comment]
Something is really wrong here. This one reverts version 3 changes back to version 2.

**Comment by panther2** [comment]
@simon33-2 It is redundant indeed. It was just a different attempt to what has been merged with #39 .
So we can really close and forget this one safely.

**Comment by panther2** [comment]
@regularkyd Would you please close this PR?
It's all done.

**Comment by simon33-2** [comment]
Closing as it's redundant.

**Pull request closed without merging**
