### PR TITLE
Fixes Vichy Bug

### PR DESCRIPTION
**Pull request by simon33-2**
Strange bug with triggering/not triggering Vichy incorrectly. Can't recall which way around it was.

### CODE REVIEW

**Comment by simon33-2** [comment]
Also add maps with combat move before purchase.

Added to note about combat move with the only valid landing site to a newly purchased carrier needs an edit mode fix on these maps.

**Comment by simon33-2** [comment]
@DanVanAtta @ron-murhammer 
Can someone merge this? Does anyone else have write access?

**Comment by panther2** [comment]
In this context - can we have a decision on #9 ?

We would have 9 files inside the game-subfolder if we keep those files that are no longer needed/updated.

**Comment by simon33-2** [comment]
@panther2 
I've added removing those three files to this PR.

**Comment by ron-murhammer** [comment]
@simon33-2 @panther2 Can one of you list the changes that are being done with the PR and why? Also can you confirm you tested after making those changes.

**Comment by panther2** [comment]
@ron-murhammer 

Please see issue #9 to understand my point. We don't need 9 game.xml inside the game folder, because three of them are obsolete, IMHO.

I am not familiar with the balance mod, so I cannot comment on this. I am sure @simon33-2 will do.

**Comment by simon33-2** [comment]
Hi @ron-murhammer 
This PR resolves an issue with the balanced mod map where Vichy is incorrectly triggered in spite of the presence in Southern France of a british land unit. (Or at least I'm told it does)

It also adds a couple of other slightly different maps (one each for 2nd ed and balanced mod) which have combat move before purchase.
Finally it removes the two redundant .txt files from the game directory and the Alpha+3 map which Panther (who would know) tells us that no one plays.

Regarding testing, I have tested the addition of the extra map(s) but I haven't tested the Vichy change - I just copied the change from elsewhere. If I get a chance this morning, I'll have a go at that.

**Comment by simon33-2** [comment]
Ok, now I've tested it. (oops, needed a change!)

**Comment by simon33-2** [comment]
@ron-murhammer

**Comment by ron-murhammer** [comment]
@simon33-2 @panther2 Merging this. One note is that I don't want to keep adding lots of variations to the core global 40 download and if we get any more then we'll need to most likely break them of into a separate download. This tends to cause lots of confusion for newer players around what map is the core and which are variations. 

Please test and make a pull request in the main repo to increment the download version number when ready.

**Comment by simon33-2** [comment]
Thanks @ron-murhammer

**Pull request merged**
