### PR TITLE
Remove some information from readme.md

### PR DESCRIPTION
**Pull request by panther2**
There are some more games inside this map, than only Oztea's setup.
Either we list all of them or none, IMHO.

### CODE REVIEW

**Comment by beelee1** [comment]
@panther2
I just added the oztea xml to the games folder with all the other xmls.  Maybe I was supposed to just add the oztea xml ?  Also do you know where triplea-game repo is ? A git search didn't turn anything up and the link at Update Triplea_maps.yaml is broken.

**Comment by panther2** [comment]
@beelee1 
Don't worry, it was only the oztea.xml that has been merged. Indeed, there was no need to touch the readme.md, but this is no big deal.

Here is the triplea-game repo:
https://github.com/triplea-game/triplea

And this is the correct link to the Triplea-maps.yaml:
https://github.com/triplea-game/triplea/blob/master/triplea_maps.yaml

**Comment by beelee1** [comment]
Right on man. Thanks

**Comment by panther2** [comment]
@beelee1 

We do map updates in full numbers, so it would be version 7 as of now.
Yes, you could add something like "Oztea's 1941 setup" to the sentence that starts with "Now also includes Balanced Mod...."

**Comment by panther2** [comment]
@simon33-2 

Would you take care of this PR, please? Thank you.

**Pull request merged**
